config/routes.rb
Rails.application.routes.draw do
  resources :ads 
    match 'ads/types/:type' => 'ads#index', via: [:get]   
  
  devise_for :users

   root to: "ads#index"
   

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /ads
  # GET /ads.json
  def index
  #byebug 
  #   console

    if params[:type].present?
      @ads = Ad.where(typ: params[:type])
    else  
      @ads = Ad.all
    end  
  
    #@ads = Ad.find(1,2,3)
    #@ads = Ad.where(typ:'floor finishes')
    #@ads = Ad.first(:conditions => "typ = 'floor finishes'")
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:name, :size, :colour, :description, :base, :dryingtime, :coverage, :price, :image, :typ)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<%= form_for(@ad) do |f| %>
  <% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% @ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.cktext_area :description %>
  </div>
  <div class="field">
    <%= f.label :base %><br>
    <%= f.text_field :base %>
  </div>
  <div class="field">
    <%= f.label :dryingtime %><br>
    <%= f.text_field :dryingtime %>
  </div>
  <div class="field">
    <%= f.label :coverage %><br>
    <%= f.text_field :coverage %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :typ %><br>
    <%= f.text_field :typ %>
  </div>

  
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<p id="notice"><%= notice %></p>

    <% @ads.each  do |ad| %>
     
      <div class="col-md-2">
        <%= image_tag ad.image ,class: "img-responsive" %>        
      </div>
     
      <div class="col-md-10">
        <div class="col-md-12">
          <h4><%= link_to ad.name, ad %></h4>  
        </div>
        <div class="col-md-6">
          <strong>Size: </strong><%= ad.size %>
        </div>  
        <div class="col-md-6">
          <strong>Base: </strong><%= ad.base %>
        </div>  
        <div class="col-md-6">
          <strong>Colour: </strong><%= ad.colour %>
        </div>  
        
      </div>
      
      <div class="col-md-12">
        <hr>
      </div>
      
    <% end %>

app/views/ads/new.html.erb
<h1>New Ad</h1>

<%= render 'form' %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ad.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @ad.size %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @ad.colour %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>

<p>
  <strong>Base:</strong>
  <%= @ad.base %>
</p>

<p>
  <strong>Dryingtime:</strong>
  <%= @ad.dryingtime %>
</p>

<p>
  <strong>Coverage:</strong>
  <%= @ad.coverage %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ad.price %>
</p>

<p>
  <strong>Typ:</strong>
  <%= @ad.typ %>
</p>


<%= link_to 'Edit', edit_ad_path(@ad) %> |
<%= link_to 'Back', ads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rustins</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body> 
  
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/ads">Rustin Paints</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu">
            
            <li><%= link_to("Wood preparation", ads_path(type: "wood_preparation")) %></li>
            <li role="separator" class="divider"></li>
            
            <li><%= link_to("Outdoor wood finishes", ads_path(type: "outdor_wood_finishes")) %></li>
            <li role="separator" class="divider"></li>
            
            <li><%= link_to("Indoor wood finishes", ads_path(type: "indoor_wood_finishes")) %></li> 
            <li role="separator" class="divider"></li>
            
            <li><%= link_to("Floor finishes", ads_path(type: "floor_finishes")) %></li>
            <li role="separator" class="divider"></li>
            
            <li><%= link_to("Specjality products", ads_path(type: "speciality_products")) %></li>
            <li role="separator" class="divider"></li>
            
            <li><%#= link_to("Decorating products", controller: 'ads', action: 'index', type: 'decorating_products') %></li>
            <li role="separator" class="divider"></li>
          
            <li><%#= link_to("Renowators", controller: 'ads', action: 'index', type: 'renovators') %></li> 
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      

      <ul class="nav navbar-nav navbar-right">
       

       <% if current_user %>
         <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
       <% else %>
         <li><%= link_to 'Sign in or register', new_user_session_path %></li>
       <% end %>


      </ul>
    


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


  <div class="container-fluid">  
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>  
    </div>  
  </div>

</body>

</html>